@startuml
title Diagramme de déploiement [eqp32 & pcoieffey]
actor Utilisateur as User


node "<i><<Device>></i>\nClient" as Client {
    component "Terminal" as progClient
}


node "<i><<Device>></i>\nServeur" as Serveur {
    component "Application serveur" as progServeur
    component "ODM DataStax Python Driver" as ODM
    note bottom of ODM : <i>Object data-store mapping tool</i>

    component "\n<b>Cassandra File System</b>" as CFS {
        storage "Cluster Cassandra" as cluster {
            database "Nœud Cassandra" as noeud1
            database "Nœud Cassandra" as noeud2
            database "Nœud Cassandra" as noeud3
            database "Nœud Cassandra" as noeud4
        }
    }
}

User -- progClient
progServeur -- ODM
ODM -right- CFS
progClient -down- progServeur

noeud1 -down- noeud2
noeud2 -right- noeud3
noeud3 -up- noeud4
noeud4 -left- noeud1
@enduml
